version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
  aws-ecs: circleci/aws-ecs@1.3.0

jobs:
  test_backend:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:5.7.30

    working_directory: ~/repo

    steps:
      - checkout

      # restore gem from cache
      - run:
         name: docker-compose up
         command: |
          docker-compose up -d --build
      - run:
         name: RSpec
         command: docker-compose exec -d backend bundle exec rspec spec/models

      - run:
         name: docker-compose down
         command: |
          docker-compose down

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
      - store_artifacts:
          path: /home/circleci/repo/tmp/screenshots

          
  build_and_push_image_backend:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          repo: "zenn-app-backend"
          region: AWS_REGION
          tag: "${CIRCLE_SHA1}"
          path: ./backend/

workflows:
  version: 2
  test:
    jobs:
      - test_backend:
          filters:
            branches:
              ignore: main
      - build_and_push_image_backend:
          requires:
            - test_backend
          filters:
            branches:
              only: main
      - aws-ecs/deploy-service-update:
          requires:
            - build_and_push_image_backend
          family: "zenn-app-task-backend"
          service-name: "zenn-app-service-backend"
          cluster-name: "production"
          container-image-name-updates: "container=zenn-app-container-backend,tag=${CIRCLE_SHA1}"
          filters:
            branches:
              only: main
  test_and_deploy:
    jobs:
      - test_backend:
          filters:
            branches:
              only: main
      - build_and_push_image_backend:
          requires:
            - test_backend
          filters:
            branches:
              only: main
      - aws-ecs/deploy-service-update:
          requires:
            - build_and_push_image_backend
          family: "zenn-app-task-backend"
          service-name: "zenn-app-service-backend"
          cluster-name: "production"
          container-image-name-updates: "container=zenn-app-container-backend,tag=${CIRCLE_SHA1}"
          filters:
            branches:
              only: main
